name: Python Validation

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: actions/cache@v3
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
    - name: Install pipenv
      run: python -m pip install --upgrade pipenv wheel
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - name: Install dependencies
      run: |
        pipenv install --dev
        pipenv run maturin develop --manifest-path crates/zspell-py/Cargo.toml
    - name: Pytest
      run: pipenv run pytest
    - name: Validate docs
      run: pipenv run make -C crates/zspell-py/docs html
